### ISSUE TITLE
Splicing order reversed

### ISSUE THREAD

**Issue by yallop** [modular-macros/ocaml-macros#10]
```
$ cat splices.ml 
macro one = << 1 >>
macro two = << 2 >>
macro three = << 3 >>

let () =
  begin
    Printf.printf "%d\n" $(one);
    Printf.printf "%d\n" $(two);
    Printf.printf "%d\n" $(three);
  end
$ ocaml splices.ml 
3
2
1
```

And if the splices have different types:

```
$ cat tsplices.ml 
macro one = << 1 >>
macro two = << "two" >>

let () =
  begin
    Printf.printf "%d\n" $(one);
    Printf.printf "%s\n" $(two);
  end
$ ocaml tsplices.ml 
Segmentation fault
```

**Comment by lpw25** [comment]
Just to check, is this also with the macros_old branch?

**Comment by yallop** [comment]
Yes.

**Comment by OlivierNicole** [comment]
I closed the issue by mistake.
This is embarrassing… I did have this bug mid-2016, I thought I had fixed it.

**Comment by OlivierNicole** [comment]
This should be fixed by 42a00617d75290056c2632c6f73b792432584f3d. 894b17b64c3d707aff90b398adda8be2ee2193d7 also adds an ordering test to prevent such an obvious problem to go unnoticed again.

The parts of `Translmod` managing splices are also cleaner now.

**Comment by yallop** [comment]
Indeed, 42a0061 has fixed the issue for me.

**Comment by yallop** [comment]
Thanks!

**Comment by OlivierNicole** [comment]
The tests in `lib-dynlink-csharp` are failing, but they already were before my changes on `macros_old`. I don't really now what these tests do.
