### ISSUE TITLE
Fatal error with static/macro mismatch between implementation and interface

### ISSUE THREAD

**Issue by yallop** [modular-macros/ocaml-macros#12]
(This is with the `macros_old` branch)

Having either `static` in the implementation and `macro` in the signature (for the same identifier) or vice versa leads to a compiler crash. 

Here's the behaviour with a `macro` interface for a `static` member:
```
$ cat stat.ml
module M : sig macro  f : 'a -> 'a end =
        struct static f    x =   x end

let _ = $(M.f <<()>>)
$ ocamlc stat.ml
Segmentation fault
>> Fatal error: Something went wrong when executing splice generation command: /home/jeremy/.opam/4.04.0+macros/bin/ocamlrun /tmp/camlstatic907e44 /tmp/camlsplice256246
Fatal error: exception Misc.Fatal_error
```

And here's the behaviour with a `static` interface for a `macro` member:
```
$ cat stat2.ml
module M : sig static val f : 'a -> 'a end =
        struct macro      f    x =   x end

let _ = $(M.f <<()>>)

$ ocamlc stat2.ml
Segmentation fault
>> Fatal error: Something went wrong when executing splice generation command: /home/jeremy/.opam/4.04.0+macros/bin/ocamlrun /tmp/camlstaticbab7a2 /tmp/camlsplice5b6871
Fatal error: exception Misc.Fatal_error
```

**Comment by lpw25** [comment]
This should probably be being caught by [Include_core.value_description](https://github.com/ocamllabs/ocaml-macros/blob/macros_old/typing/includecore.ml#L27) based on the `value_kind` field of the value description. That's how we stop a similar issue with `val` vs. `external`.
