### ISSUE TITLE
[Question] When will this be merged upstream ? 

### ISSUE THREAD

**Issue by abhi18av** [modular-macros/ocaml-macros#14]
Hi OCaml team,

I was wondering whether this macro system for `OCaml` is supposed to be released in the general distribution ?

**Comment by yallop** [comment]
We're hoping to incorporate this into the general distribution eventually, but there's still some work to do, both practical (implementation) and theoretical (formalisation) before it's ready.

**Comment by abhi18av** [comment]
I understand @yallop , thanks for the quick revert 👍 

Is there any general timeline beyond `multicore-ocaml` that the team wishes to take this up again ? I understand the new runtime is nearing it's release pretty soon and it requires your efforts.

But this is another great thing to be had in `OCaml` and I can't wait for this to be generally available :)

**Comment by abhi18av** [comment]
@yallop , could you please elaborate or point me towards some resources which highlight the different use cases of `macros` and `metaocaml` i.e. `multi stage programming` ? 

I've become really curious about the things happening around `OCaml` in academia :)

**Comment by yallop** [comment]
The central difference is that macros are for generating code at compile time and MetaOCaml is for generating code at run time.  So, for example
* for building an optimized executable based on information available during compilation (e.g. configuration), use macros
* for generating optimized code based on run-time information (e.g. a regex supplied by a user), use MetaOCaml

It's possible to combine both compile-time and run-time code generation in the same system, using the same language constructs, as @nicolasstucki, @biboudis and @odersky show in their paper published at GPCE'18 last month:

> A Practical Unification of Multi-stage Programming and Macros (GPCE 2018)  
> by Nicolas Stucki, Aggelos Biboudis and Martin Odersky  
> https://biboudis.github.io/papers/pcp-gpce18.pdf

It's possible that we'll eventually take a similar approach in OCaml.

**Comment by abhi18av** [comment]
Wonderful!

I'm really looking forward towards all these features in the `OCaml` language :)
